steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - main-project/backend/docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - main-project/backend/docker-compose.prod.yaml
      - push

  # 3단계 => kubectl set image deployment/mybackend-nestjs mybackend-nestjs-sha256-1=asia.gcr.io/optimistic-air-370203/mybackend10-nestjs:5.0
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/mybackend-nestjs
      - mybackend-nestjs-sha256-1=asia.gcr.io/optimistic-air-370203/mybackend10-nestjs:5.2
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-2
