version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/optimistic-air-370203/mybackend10-nestjs:5.2
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - ./.env.prod
    # ports:
    #   - 3000:3000
